name: push_ci
run-name: Push CI
on:
  push:
    branches:
      - ci
jobs:
  linux-aarch64:
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Build Script
        run: sh ./ci/linux/build-aarch64.sh
  macos-x86_64:
    strategy:
      matrix:
        version: ["11", "12"]
    runs-on: "macos-${{ matrix.version }}"
    env: 
      ARCH: "x86_64"
      MACOS_VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Build Script
        run: ./ci/macos/build-x86_64.sh
  macos-aarch64:
    runs-on: [self-hosted, macOS, aarch64]
    env: 
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Build Script
        run: ./ci/macos/build-aarch64.sh
  windows:
    runs-on: windows-latest
    env: 
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run Build Script
        run: ./ci/windows/build.ps1
